# Generated by Django 4.2.6 on 2023-10-08 11:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BUILDING')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, null=True)),
                ('floors', models.IntegerField(default=1)),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.buildingtype')),
            ],
        ),
    ]
